-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.accounts_account_number_seq;

CREATE SEQUENCE public.accounts_account_number_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.atm_atm_id_seq;

CREATE SEQUENCE public.atm_atm_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.branches_branch_id_seq;

CREATE SEQUENCE public.branches_branch_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.cards_card_number_seq;

CREATE SEQUENCE public.cards_card_number_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.customers_customer_id_seq;

CREATE SEQUENCE public.customers_customer_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.employees_employee_id_seq;

CREATE SEQUENCE public.employees_employee_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.loan_types_loan_type_id_seq;

CREATE SEQUENCE public.loan_types_loan_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.loans_loan_id_seq;

CREATE SEQUENCE public.loans_loan_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.transaction_status_status_id_seq;

CREATE SEQUENCE public.transaction_status_status_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.transactions_transaction_id_seq;

CREATE SEQUENCE public.transactions_transaction_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.branches definition

-- Drop table

-- DROP TABLE public.branches;

CREATE TABLE public.branches (
	branch_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	branch_name varchar(255) NULL,
	"location" varchar(255) NULL,
	branch_phone varchar(20) NULL,
	branch_email varchar(100) NULL,
	manager_id int4 NULL,
	operating_hours varchar(50) NOT NULL,
	CONSTRAINT branches_pkey PRIMARY KEY (branch_id)
);


-- public.loan_types definition

-- Drop table

-- DROP TABLE public.loan_types;

CREATE TABLE public.loan_types (
	loan_type_id serial4 NOT NULL,
	loan_category varchar(50) NOT NULL,
	base_interest_rate numeric(6, 4) NOT NULL,
	base_amount numeric(15, 2) NOT NULL,
	description varchar(255) NULL,
	CONSTRAINT loan_types_pkey PRIMARY KEY (loan_type_id)
);


-- public.atm definition

-- Drop table

-- DROP TABLE public.atm;

CREATE TABLE public.atm (
	atm_id serial4 NOT NULL,
	branch_id int4 NULL,
	"location" varchar(50) NULL,
	status varchar(20) NULL,
	operating_hours varchar(50) NULL,
	supported_transactions varchar(20) NULL,
	CONSTRAINT atm_pkey PRIMARY KEY (atm_id),
	CONSTRAINT fk_atm_branches FOREIGN KEY (branch_id) REFERENCES public.branches(branch_id)
);


-- public.customers definition

-- Drop table

-- DROP TABLE public.customers;

CREATE TABLE public.customers (
	customer_id serial4 NOT NULL,
	branch_id int4 NULL,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	address varchar(100) NULL,
	city varchar(50) NULL,
	gender bpchar(1) NULL,
	state varchar(50) NULL,
	country varchar(50) NULL,
	phone varchar(20) NULL,
	email varchar(50) NULL,
	date_of_birth date NOT NULL,
	ssn varchar(20) NULL,
	CONSTRAINT customers_pkey PRIMARY KEY (customer_id),
	CONSTRAINT fk_customers_branches FOREIGN KEY (branch_id) REFERENCES public.branches(branch_id)
);


-- public.employees definition

-- Drop table

-- DROP TABLE public.employees;

CREATE TABLE public.employees (
	employee_id serial4 NOT NULL,
	branch_id int4 NULL,
	"name" varchar(50) NULL,
	"position" varchar(30) NULL,
	emp_phone varchar(20) NULL,
	emp_email varchar(50) NULL,
	gender bpchar(1) NULL,
	hire_date date NULL,
	qualification varchar(25) NULL,
	CONSTRAINT employees_pkey PRIMARY KEY (employee_id),
	CONSTRAINT fk_employees_brach FOREIGN KEY (branch_id) REFERENCES public.branches(branch_id)
);


-- public.loans definition

-- Drop table

-- DROP TABLE public.loans;

CREATE TABLE public.loans (
	loan_id serial4 NOT NULL,
	customer_id int4 NULL,
	loan_type_id int4 NULL,
	branch_id int4 NULL,
	loan_amount numeric(15, 2) NOT NULL,
	interest_rate numeric(6, 4) NOT NULL,
	term_months int4 NOT NULL,
	start_date date NOT NULL,
	end_date date NOT NULL,
	status varchar(20) NULL,
	CONSTRAINT loans_pkey PRIMARY KEY (loan_id),
	CONSTRAINT loans_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('CLOSED'::character varying)::text, ('DEFAULTED'::character varying)::text, ('PENDING'::character varying)::text]))),
	CONSTRAINT fk_loans_branches FOREIGN KEY (branch_id) REFERENCES public.branches(branch_id),
	CONSTRAINT fk_loans_customers FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id),
	CONSTRAINT fk_loans_loan_types FOREIGN KEY (loan_type_id) REFERENCES public.loan_types(loan_type_id)
);


-- public.accounts definition

-- Drop table

-- DROP TABLE public.accounts;

CREATE TABLE public.accounts (
	account_number serial4 NOT NULL,
	customer_id int4 NULL,
	account_type varchar(20) NULL,
	balance numeric(16, 2) NULL,
	account_status varchar(20) NULL,
	registration_date date NULL,
	open_date date NULL,
	closed_date date NULL,
	CONSTRAINT accounts_pkey PRIMARY KEY (account_number),
	CONSTRAINT fk_accounts_customers FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id)
);


-- public.cards definition

-- Drop table

-- DROP TABLE public.cards;

CREATE TABLE public.cards (
	card_number varchar(20) DEFAULT nextval('cards_card_number_seq'::regclass) NOT NULL,
	customer_id int4 NULL,
	card_type varchar(20) NULL,
	exp_date date NULL,
	card_status varchar(20) NULL,
	CONSTRAINT cards_pkey PRIMARY KEY (card_number),
	CONSTRAINT fk_cards_customers FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id)
);


-- public.transactions definition

-- Drop table

-- DROP TABLE public.transactions;

CREATE TABLE public.transactions (
	transaction_id serial4 NOT NULL,
	account_number int4 NOT NULL,
	transaction_type varchar(20) NULL,
	amount numeric(16, 2) NOT NULL,
	date_time timestamp NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id),
	CONSTRAINT fk_transactions_accounts FOREIGN KEY (account_number) REFERENCES public.accounts(account_number)
);


-- public.transaction_details definition

-- Drop table

-- DROP TABLE public.transaction_details;

CREATE TABLE public.transaction_details (
	transaction_id int4 NOT NULL,
	description varchar(20) NULL,
	merchant_payee varchar(20) NULL,
	transaction_category varchar(20) NULL,
	currency varchar(20) NULL,
	notes varchar(255) NULL,
	CONSTRAINT transaction_details_pkey PRIMARY KEY (transaction_id),
	CONSTRAINT fk_transactions_trnsaction_details FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id)
);


-- public.transaction_status definition

-- Drop table

-- DROP TABLE public.transaction_status;

CREATE TABLE public.transaction_status (
	status_id serial4 NOT NULL,
	transaction_id int4 NULL,
	status_type varchar(25) NOT NULL,
	description varchar(255) NULL,
	"time" timestamp NULL,
	CONSTRAINT transaction_status_pkey PRIMARY KEY (status_id),
	CONSTRAINT fk_trasaction_status_transations FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id)
);